/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';




export namespace Components {

  interface AglAddressSearch {
    'redirect': string;
  }
  interface AglAddressSearchAttributes extends StencilHTMLAttributes {
    'redirect'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AglAddressSearch': Components.AglAddressSearch;
  }

  interface StencilIntrinsicElements {
    'agl-address-search': Components.AglAddressSearchAttributes;
  }


  interface HTMLAglAddressSearchElement extends Components.AglAddressSearch, HTMLStencilElement {}
  var HTMLAglAddressSearchElement: {
    prototype: HTMLAglAddressSearchElement;
    new (): HTMLAglAddressSearchElement;
  };

  interface HTMLElementTagNameMap {
    'agl-address-search': HTMLAglAddressSearchElement
  }

  interface ElementTagNameMap {
    'agl-address-search': HTMLAglAddressSearchElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
